- .github/workflows/deploy.yml
- app/.env.tpl
- app/.eslintrc.json
- app/components/backup/chats.tsx
- app/components/backup/connect.tsx
- app/components/dashboard/backed-chats.tsx
- app/components/dashboard/backup.tsx
- app/components/layouts/menu.tsx
- app/components/leaderboard/users.tsx
- app/components/root.tsx
- app/components/telegram-auth.tsx
- app/package.json
- pnpm-lock.yaml
configure eslint and clean up the code
> chore: add linting, delint code

- app/components/dashboard/head.tsx
- app/components/layouts/menu.tsx
- app/components/root.tsx
- app/components/telegram-auth.tsx
- app/providers/telegram.tsx
- app/zustand/global.ts
Adds a provider that adds a telegram client, the launch params and the user from `initData` to the context.
Usage:
```ts
import { useTelegram } from '@/providers/telegram'
export const Component = () => {
const [{ client, user }] = useTelegram()
return <p>{user?.firstName}</p>
}
```
> feat: add telegram provider

- app/components/backup/dates.tsx
- app/components/backup/summary.tsx
Switches the period to seconds, and changes `to` time to be `undefined` instead of `Infinity`.
> refactor: period in seconds

- app/components/layouts/menu.tsx
- app/zustand/global.ts
Previously the storacha data was left in indexdb.
> fix: logout from storacha

- app/components/backup/chats.tsx
- app/components/layouts/index.tsx
Using the query string means the history gets messed up when navigating back from the first step. There's no access to the URL anyway so there is no need for this to be run from it.
resolves https://github.com/storacha/tg-miniapp/issues/35
> fix: back button when creating backup

- app/api.ts
- app/lib/backup/runner.ts
- app/lib/utils.ts
Also some fixes to the types.
Note: where the Telegram type can be `*Empty` we use `undefined`.
resolves https://github.com/storacha/tg-miniapp/issues/40
> feat: implement backup of service messages

- app/app/dialog/[id]/page.tsx
- app/components/dashboard/backed-chats.tsx
- app/components/ui/media.tsx
- app/lib/backup/runner.ts
- app/package.json
- app/providers/backup.tsx
- pnpm-lock.yaml
- Add retrieval, decoding, decryption, and visualization of backed-up messages.
- Fix missing messages bug in a chat with a single user
> feat: retrieve backup from storacha

- .github/workflows/deploy.yml
- app/.env.tpl
- app/app/dialog/[id]/page.tsx
Use the production gateway if not set.
> fix: default gateway URL

- docs/schema.md
Adds documentation that details the schema for the backup data.
> docs: add schema documentation

- app/api.ts
- app/lib/backup/runner.ts
This PR adds types for all the media. But it does not encode them into the backup yet.
> feat: add media types

- app/lib/backup/recoverer.ts
- app/lib/backup/runner.ts
- docs/schema.md
This PR encrypts the root block of the backup for additional privacy.
> fix: encrypt root block

- app/app/dialog/[id]/backup/[cid]/page.tsx
- app/app/page.tsx
- app/components/dashboard/backed-chats.tsx
- app/components/layouts/chat-header.tsx
- app/components/layouts/index.tsx
- app/lib/utils.ts
This PR resolves #65  and also fixes the chat header in the backup visualization.
> chore: add UI tweaks

- app/app/dialog/[id]/backup/[cid]/page.tsx
- app/app/dialog/[id]/page.tsx
- app/app/page.tsx
- app/components/dashboard/backed-chats.tsx
- app/components/layouts/chat-header.tsx
- app/components/layouts/index.tsx
- app/lib/backup/runner.ts
- app/lib/backup/utils.ts
- app/lib/utils.ts
This PR adds the backup select screen
resolves #64
> feat: add select backup screen

- app/api.ts
- app/app/dialog/[id]/backup/[cid]/page.tsx
- app/components/layouts/chat-header.tsx
- app/components/ui/media.tsx
- app/lib/backup/recoverer.ts
- app/lib/backup/runner.ts
- app/package.json
- pnpm-lock.yaml
This PR adds media visualization to chat dialogs
**Media Preview:**
* Image example: 
* Poll example:
* File and Location:
* Audio example:
* GIF and Emoji:
> feat: add media visualization

- CONTRIBUTING.md
- README.md
- app/.env.tpl
This PR resolves https://github.com/storacha/tg-miniapp/issues/84 .
> chore: update readme and contributing guide

- app/api.ts
- app/app/dialog/[id]/backup/[cid]/page.tsx
- app/components/backup/chats.tsx
- app/components/dashboard/backed-chats.tsx
- app/components/layouts/menu.tsx
- app/components/root.tsx
- app/components/server.ts
- app/components/telegram-auth.tsx
- app/lib/backup/sender.ts
- app/lib/server/server.ts
- app/lib/server/telegram-manager.ts
- app/providers/telegram.tsx
- app/zustand/global.ts
> fix: auth key duplicated

- app/app/backup/page.tsx
- app/app/dialog/[id]/backup/[cid]/page.tsx
- app/app/dialog/[id]/page.tsx
- app/components/backup/chats.tsx
- app/components/backup/dialog-item.tsx
- app/components/dashboard/backed-chats.tsx
- app/components/ui/loading.tsx
This PR addresses several UI issues and inconsistencies in the dialog and backup flow.
* Fixed "Dialog not found" flash that briefly appeared before backed-up dialog is loaded
* Show only backed-up chats on home page
* Remove duplicate DialogItem component
* Display "All time" instead of 1969 date on backup selection
* Keep "Start Backup" button disabled until navigation completes
> chore: UI improvements and bug fixes

- app/components/dashboard/backed-chats.tsx
If you have 0 backups, the storacha icon should stay up on the dashboard.
> fix(dashboard): show safe icon if there aren't backups

- app/app/backup/page.tsx
- app/components/backup/connect.tsx
- app/components/dashboard/backed-chats.tsx
- app/components/dashboard/index.tsx
- app/components/root.tsx
- app/components/server.ts
- app/lib/server/constants.ts
- app/zustand/global.ts
- `StorachaConnect` now appears at appropriate stages based on user status
- Improved logic for first-time login detection and returning user experience
> chore: move Storacha login flow to first page

- app/components/backup/connect.tsx
> fix: add error message for expired email verification link

- app/api.ts
- app/app/dialog/[id]/backup/[cid]/page.tsx
- app/app/dialog/[id]/page.tsx
- app/lib/backup/recoverer.ts
- app/providers/backup.tsx
this is so people can navigate back to the previous page if the loading is endless
closes #164
> chore: show header component when a backed up chat is loading messages

- app/app/dialog/[id]/backup/[cid]/page.tsx
- app/lib/server/runner.ts
> fix: show empty backup instead of throwing an error

- app/lib/server/telegram-manager.ts
The Telegram client logs numerous `[Error: TIMEOUT]` messages during normal operation. These errors are logged directly via `console.error() `bypassing the library's logger system, making them impossible to control through the standard logging configuration.
**Root Cause**
The gramjs library's internal ping mechanism generates TIMEOUT errors when server pings exceed 10 seconds.  
This create excessive noise in the logs without providing actionable information.
> chore: suppress telegram client TIMEOUT error logs

- app/components/ui/media.tsx
> fix: lazy load image media

- .github/actions/env-setup/action.yml
- .github/workflows/test.yml
- app/package.json
still a bit of work to bring this to parity with the bluesky app, but this will at least catch build and lint errors
> fix: add build and test to CI

- .gitignore
- scripts/db-tunnel/template
details for each environment are in 1password - please talk to @travis or @hannahhoward to get access
> chore: add template for script to access staging and prod dbs

- .gitignore
> fix: ignore .claude

- app/app/api/jobs/route.ts
- app/package.json
- pnpm-lock.yaml
Our long running backup jobs are failing cause the http endpoint is timing out. I'm not sure if this will fix this but I can't test until the build is fixed.
> fix(jobs): run processing asyncronously

- app/components/dashboard/head.tsx
- app/components/leaderboard/podium.tsx
- app/components/leaderboard/users.tsx
- app/hooks/useUserLocale.ts
- app/lib/storacha.ts
- app/lib/utils.ts
- **Fix usage report period:** Now starts at the beginning of the month to avoid missing previous month’s data.
-  **Points display:** Shows 1 decimal and formats according to user’s locale.
> fix: points display and usage report request

- app/components/server.ts
- app/lib/server/db.ts
we were only loading names for the top 3 users, but we don't want to do this anyway!
there's still some work to do getting the image right here but I think that should be on the client side - I'm going to leave that for a future PR
> fix: correct percentile calc and load my name no matter where I am

- app/app/dialog/[id]/backup/[cid]/page.tsx
- app/components/backup/useProfilePhoto.tsx
- app/components/root.tsx
- app/lib/backup/recoverer.ts
- app/package.json
- pnpm-lock.yaml
- Fixes #301 by removing the update to the mediaMap before the callback being called
- Fixes storacha client configuration
- Add gateway requests rate limit and retry logic.
PS: About the rate limit. Although our gateway doesn’t have it enabled in the code, Cloudflare’s own security rules apply. When a single IP makes more than 200 requests per minute, it gets blocked for 1 minute.
> fix: loading backup and images 

- app/app/dialog/[id]/backup/[cid]/page.tsx
- app/app/leaderboard/page.tsx
- app/components/server.ts
- app/lib/server/db.ts
- app/providers/backup.tsx
- app/providers/telegram.tsx
- Fixed app crash when viewing a backup  (`undefined is not an object (evaluating 'd[e.from].photo')`)
- Fixed inconsistent ranking numbers between leaderboard banner and list
- Reset dialogs and offset parameters after logout  (attempt to fix `Error fetching dialogs: Could not find entity for...`)
- Forced backup list refresh after delete
Some issues I couldn’t fully test, like deleting a backup or the “error fetching dialogs” after relogin.
> fix: multiple UI bugs

- app/app/api/entity/[id]/image/route.ts
- app/app/dialog/[id]/backup/[cid]/page.tsx
- app/components/server.ts
- app/lib/server/jobs.ts
- app/lib/server/telegram-manager.ts
- app/providers/error.tsx
- Fix memory leak from getTelegramClient 
- improve the Error provider to remove setTimeout
> fix: memory leak 

- app/app/api/entity/[id]/image/route.ts
- app/components/dashboard/head.tsx
- app/components/dashboard/index.tsx
- app/lib/backup/utils.ts
- app/lib/errorhandling.ts
* Fixes leaderboard and progress bar alignment
* Adds a user-friendly version of the `400: CONNECTION_NOT_INITED` error
* Fixes the image route entity build function
> fix: improve UI alignment, error display formatting, and entity image fetching

- app/providers/backup.tsx
Remove error popup since the issue is already reported and doesn’t significantly affect users. We constantly fetch the list of completed and pending jobs, so occasional connection errors were unnecessarily showing a popup.
> fix: update error handler on backup

- app/components/server.ts
- app/lib/errorhandling.ts
- app/lib/server/db.ts
- app/lib/server/telegram-manager.ts
- Fixed error caused by large payloads in SQL notify events
- Removed unnecessary log lines to reduce noise
> fix: handle sql notify payload issue

- app/lib/server/db.ts
- app/lib/server/jobs.ts
- app/lib/server/runner.ts
- Fix error message in `db.getJobByID`
- Return a clearer message to the user when a job is not found during removal
- Add try/catch around `uploadCar`
> fix: remove job
