storacha/tg-miniapp

app/components/backup/chats.tsx, app/components/dashboard/backed-chats.tsx, app/components/dashboard/index.tsx, app/components/layouts/menu.tsx, app/lib/backup/manager.ts, app/lib/backup/runner.ts, app/lib/store/cloudstorage-backups.ts, app/lib/store/localstorage-jobs.ts
* Display datetime of latest backup next to chat in both the dashboard and chat selection for backup 
* Display "Never" in danger red
Also some general tweaks:
* Temporarily hide the points/leaderboard section on the dashboard
* Temporarily hide the storage usage progress bar in the menu
* Store list of backups/jobs with most recent first (this should make sorting them faster)
* Add a progress callback `onDialogRetrieved` when we downloaded all the messages but did not encrypt/store them yet - more progress events = more user feedback that something is happening
=> feat: show latest backup time

app/api.ts, app/lib/backup/runner.ts
Add message `type` field and definitions for both types: regular and "service".
Necessary follow on for service messages: https://github.com/storacha/tg-miniapp/issues/40
Follow on for regular messages: https://github.com/storacha/tg-miniapp/issues/41
=> feat: add message types

app/api.ts, app/lib/backup/runner.ts
This PR adds types for all the service messages, however it does not yet encode them into the backup.
All union types have an additional "unknown" type to capture new types that the app does not yet know about.
=> feat: service message types

app/api.ts, app/app/dialog/[id]/page.tsx, app/components/dashboard/backed-chats.tsx, app/lib/backup/recoverer.ts, app/lib/backup/runner.ts, app/package.json, app/providers/backup.tsx
This PR includes some improvements requested in #53 
- Adds lazy loading for messages, so we no longer buffer the entire chat history in memory.  
- Adds `peer` field to `MessageData`.  
- Cleans up unused `dialog` and `setDialog` from the Backup provider.  
- Moves `restoreBackup` logic from the page to the Backup provider.
=> refactor: improve loading visualization

app/api.ts, app/lib/backup/runner.ts, app/lib/backup/utils.ts, docs/schema.md
📦  **Media Backup Support**
This PR adds support for backing up media files along with their associated metadata.
* Messages can now include a link to a media file (`media.content`) and structured metadata (`media.metadata`)
* Only media types that contain an actual downloadable file will include a `media.content`. Some media types are metadata-only.
📝 **Note:**
This update does **not** include media visualization yet.
=> feat: add media backup

app/lib/server/constants.ts
This allows us to distinguish invocations made by this app vs others. Allows us to track the relative success of this application.
You may want to set `NEXT_PUBLIC_VERSION` environment var or load from `package.json` at some point...
=> feat: add x-client header

app/api.ts, app/components/dashboard/index.tsx, app/components/root.tsx, app/components/server.ts, app/lib/server/db.ts, app/lib/server/handler.ts, app/lib/server/jobs.ts, app/lib/store/jobs.ts, app/providers/backup.tsx, app/scripts/migrations/00006_add_new_status_to_jobs/index.sql
This PR introduces the ability for users to cancel backup jobs that have been in the `waiting` or `running` state for more than 24 hours (we can change this number if needed).
This does not actually remove or stop the job in the processing queue. Jobs marked as `canceled` are simply hidden from the UI.
- Users can now see a cancel (X) button for jobs stuck in `waiting` or `running` status for over a day.
- Canceling a job updates its status to `canceled` in the DB.
=> fix: allow users to cancel a stuck backup

app/api.ts, app/app/dialog/[id]/backup/[cid]/page.tsx, app/components/ui/media.tsx, app/lib/backup/recoverer.ts, app/package.json, app/providers/backup.tsx, pnpm-lock.yaml
This PR introduces an in-memory cache for the first few messages loaded by `restoreBackup` for each `backupCid:dialogId` pair, improving the speed and efficiency of opening chats. 
It also implements batch fetching for backup messages, allowing messages to be loaded in smaller chunks to improve performance and reduce initial load times.
=> perf: recover backed up chat messages in batches

app/components/dashboard/index.tsx, app/lib/server/handler.ts, app/lib/server/runner.ts, app/providers/backup.tsx
the previous computation used a static value where progress is obtained by dividing the dialogs retrieved by 2.1, which led to a ~0.48 percentage cap
now, we're splitting it into two phases. one for the retrieval, 0.7 and the other 0.3 for shard storage
=> fix: jobs progress

app/components/layouts/menu.tsx, app/components/root.tsx, app/components/telegram-auth.tsx, app/lib/server/runner.ts, app/providers/telegram.tsx, app/zustand/global.ts
This PR addresses two issues:
When backing up a chat with no messages in the selected time period, the backup would fail silently and users would see an empty visualization page without understanding why.
**Solution:** Added proper error handling to throw an error when no messages are found for a dialog in the selected period. 
**Future Consideration:** An alternative approach would be to skip empty dialogs and continue with the backup process, since there could be more dialogs to backup. We can evaluate this trade-off for now and improve it later.
When users deleted their Telegram session externally (via the Telegram app) and returned to the mini app, they encountered multiple errors instead of being redirected to re-authenticate.
**Solution:**
- Moved `isTgAuthorized` state from …
=> fix: throw error on empty backup and add session validation

app/app/dialog/[id]/page.tsx, app/components/backup/dialog-item.tsx, app/hooks/useUserLocale.ts, app/package.json, pnpm-lock.yaml
added a new hook, useUserLocale that returns a couple of functions to format date-time while considering the user's locale.
we first check for the telegram locale, if there isn't, fallback to the browser's locale.
closes #154
=> fix: format date-time in current user locale

app/components/backup/dialog-item.tsx, app/components/ui/media.tsx
While debugging #160 , I found out this is actually a valid media type supported by Telegram, `MessageMediaUnsupported`, which, according to the [docs](https://core.telegram.org/constructor/messageMediaUnsupported), means: “The current version of the client does not support this media type.”
Given that, we have two options:
1. Skip it entirely and not show anything.
2. Display a message letting the user know that the media type isn’t supported.
This PR goes with the second option.
=> fix: improve visualization to unsupported media

app/lib/server/handler.ts, app/lib/server/runner.ts, app/package.json, pnpm-lock.yaml
While debugging, I found 1 problem and implemented 1 improvement in UX:
- we were failing downloads on toDocumentAttributeData, because it was using cleanUndef instead of withCleanUndef
- I also found the UI for progress was pretty abysmal. I implemented progress tracking within an upload to make this a more pleasant experience. (among other things, it keeps backing up very large chats from appearing "stuck", and progress auto jumped to 90% for large uploads with >1 shard)
=> fix(runner): fix toDocumentAttributeData

app/components/telegram-auth.tsx, app/lib/backup/utils.ts, app/lib/server/constants.ts, app/lib/server/session.ts, app/lib/server/telegram-manager.ts
- fixes #150,  it wasn’t fully fixed because we instantiate the client in two places, but only one had the correct parameters.
- Fixes `buildDialogInputPeer`by adding a `InputPeerChat` type
=> fix: rename telegram session

app/app/api/entity/[id]/image/route.ts, app/components/backup/dialog-item.tsx, app/components/server.ts
It turns out the only way to get high quality images is to request them from the API. Furthermore, not all images are loadable using `client.getEntity` but it's difficult to determine which will work and which won't.
This PR introduces two things:
1. some client-side code to attempt to load the high quality version of an image using a new API endpoint in this app 
2. the new API endpoint itself, which tries to fetch the image a couple different ways and then sets cache headers that tell the browser to consider the image immutable
The net result here is that we'll (a) try pretty hard to load images from Telegram and then (b) aggressively cache successful results - taken alone (a) might be a cause for performance concern, but (b) should compensate pretty well for that.
=> fix: fetch high quality images for profile pictures in the list of chats

app/app/backup/page.tsx, app/components/backup/dates.tsx
The date page didn't used to require a user's Storacha account, so we didn't require first login users to log in to Storacha until later. That's no longer the case since we limit date ranges for non-paying users. Handle no account cleanly and move the Storach login dialog up a screen for first time login users.
=> fix: add StorachaConnect on date page for first login users

app/app/backup/page.tsx, app/components/backup/dates.tsx
Update calendar picker for better date range visibility
- The calendar now opens on the month of the selected start date instead of defaulting to the current month
- Visual cues were added to highlight invalid date ranges
- Dates outside the allowed range are greyed out but still selectable, with proper validation in place
=> fix: improve calendar picker

app/components/layouts/menu.tsx, app/components/telegram-auth.tsx, app/components/ui/media.tsx
- Added a default "+" prefix to the phone number input
- Adjusted the "Send PIN" button to appear above the keyboard and removed the scroll gap
- Renamed "Submit OTP" to "Submit Code" for clarity
- Removed the “Preview not available” message for links without a preview and added a skeleton image as a placeholder instead
=> fix: ui issues

.github/pull_request_template.md, .github/scripts/pr-triage.js, .github/workflows/pr-triage.yml, .github/workflows/stale-prs.yml, CONTRIBUTING.md
This PR introduces clearer contribution guidelines and an automated review workflow to improve PR quality and reduce inactive pull requests after changes are requested.
- Added labels: `awaiting-author`, `awaiting-review`, `blocked`, `security`, `maintainer-will-finish`, `stale`
- Added workflows:
1. `pr-triage.yml`
- Adds `awaiting-author` when changes are requested
- Adds `awaiting-review` on new commits or when marked `ready_for_review`
- Clears those labels when a PR is in draft
2. `stale-prs.yml`
- Marks `awaiting-author` PRs as `stale` after 10 days of inactivity and closes them 4 days later
- Exempts draft PRs and those labeled `blocked`, `security`, or `maintainer-will-finish`
=> chore: update contributing guide and add a process for PR reviews

app/components/backup/dates.tsx
- Prevents the date picker calendar from extending beyond screen
On Mac app:
<video src="https://github.com/user-attachments/assets/e87cdc4c-5d26-4ea2-ae42-182df485ac16" width="300" controls></video>
On mobile:
=> fix: prevent calendar popover from overflowing screen

app/app/api/jobs/route.ts, app/components/server.ts, app/lib/server/db.ts, app/lib/server/graceful-shutdown.ts, app/lib/server/handler.ts, app/lib/server/queue.ts, app/lib/server/telegram-manager.ts, app/lib/utils.ts, deploy/app/main.tf
- Added `GracefulShutdownManager`:
- Catches `SIGTERM` and initiates a shutdown sequence
- Tracks running job IDs in-memory (`activeJobs`)
- Requeues active jobs:
- Sends them back to SQS
- Updates DB status to `queued` (clears `started`/`progress` fields)
- Jobs Route:
- Rejects new job submissions during shutdown
- Responds with **503 Service Unavailable** and `Retry-After: 30s`
- Job Handler:
- Checks if shutdown has been initiated before handling new jobs
- Registers jobs when they start and deregisters them when they finish
obs.: I still need to test it
=> feat: add graceful shutdown for ECS SIGTERM

app/app/layout.tsx, app/components/root-loader.tsx, app/components/root.tsx
Fix the issue “Missing getServerSnapshot, which is required for server-rendered content. Falling back to client rendering,” as it’s consuming Sentry quota.
=> fix: missing getServerSnapshot
